### ISSUE TITLE
SQLite 데이터베이스

### ISSUE THREAD

**Issue by foreknowledge** [teamot/travel-together-android#11]
### Wiki
- https://github.com/teamot/travel-together-android/wiki/%EB%8D%B0%EC%9D%B4%ED%84%B0%EB%B2%A0%EC%9D%B4%EC%8A%A4-%ED%85%8C%EC%9D%B4%EB%B8%94-%EA%B5%AC%EC%A1%B0
---
### Todo
- [x] SQLite로 앱 내부 데이터베이스 구축
- [ ] BaseColumn 이용해서 id AUTO_INCREMENT 구현
- [ ] android table 데이터 확인하는 방법
